# Generated by Django 2.0.3 on 2018-04-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('tested', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('anger', 'anger'), ('disgust', 'disgust'), ('fear', 'fear'), ('happiness', 'happiness'), ('neutral', 'neutral'), ('sadness', 'sadness'), ('surprise', 'surprise')], max_length=20)),
                ('time', models.DateField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='dataFeedback.Clip')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_nums', models.IntegerField()),
                ('time', models.DateField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='dataFeedback.Clip')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypressed_num', models.IntegerField()),
                ('mouseclicked_num', models.IntegerField()),
                ('content', models.TextField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='dataFeedback.Clip')),
            ],
        ),
    ]
