# Generated by Django 2.0.3 on 2018-04-15 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotion',
            options={'ordering': ('time',)},
        ),
        migrations.AddField(
            model_name='emotion',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emotions_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operations_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
