# Generated by Django 2.0.3 on 2018-04-15 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0002_auto_20180415_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
