# Generated by Django 2.0.3 on 2018-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0003_auto_20180415_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='tested',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
