# Generated by Django 2.0.3 on 2018-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0004_auto_20180416_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='clip_outer_id',
            field=models.CharField(default='loser', max_length=255),
        ),
    ]
