# Generated by Django 2.0.3 on 2018-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0005_clip_clip_outer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='state',
            field=models.CharField(choices=[('NoFace', 'NoFace'), ('anger', 'anger'), ('disgust', 'disgust'), ('fear', 'fear'), ('happiness', 'happiness'), ('neutral', 'neutral'), ('sadness', 'sadness'), ('surprise', 'surprise')], max_length=20),
        ),
    ]
