# Generated by Django 2.0.3 on 2018-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0006_auto_20180416_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='alloperation_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clip',
            name='clip_outer_id',
            field=models.CharField(max_length=255),
        ),
    ]
