# Generated by Django 2.0.3 on 2018-04-27 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataFeedback', '0008_auto_20180416_2323'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Minutetimes',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('time', models.DateTimeField()),
        #         ('times', models.IntegerField()),
        #         ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutestimes', to='dataFeedback.Operation')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('flag', models.CharField(choices=[('close', 'close'), ('open', 'open')], max_length=20)),
                ('process_name', models.CharField(max_length=255)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='dataFeedback.Clip')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
