# Generated by Django 2.0.3 on 2018-04-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0009_minutetimes_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartbeats', models.IntegerField(null=True)),
                ('emotion', models.CharField(choices=[('NoFace', 'NoFace'), ('anger', 'anger'), ('disgust', 'disgust'), ('fear', 'fear'), ('happiness', 'happiness'), ('neutral', 'neutral'), ('sadness', 'sadness'), ('surprise', 'surprise')], max_length=20, null=True)),
                ('process_flag', models.CharField(choices=[('close', 'close'), ('open', 'open')], max_length=20, null=True)),
                ('process_name', models.CharField(max_length=255)),
                ('operation_num', models.IntegerField(default=0)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='dataFeedback.Clip')),
            ],
        ),
    ]
