# Generated by Django 2.0.3 on 2018-04-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataFeedback', '0010_minutetimes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='time',
            field=models.DateTimeField(default='1971-01-01T01:01:01'),
        ),
    ]
